# Artificial Neural Network

### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

## PART-1: Data Preprocessing

### Importing Dataset

In [3]:
dataset = pd.read_csv("Churn_Modelling.csv")
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
print(x)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


### Encoding Categorical Data

#### Label Encoding the Gender Column

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### OneHot Encoding the Geographical column

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder="passthrough")
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)

[[0.0 1.0 0.0 ... 0 1 124749.08]
 [1.0 0.0 0.0 ... 0 0 41104.82]
 [0.0 1.0 0.0 ... 1 1 45750.21]
 ...
 [1.0 0.0 0.0 ... 1 1 92027.69]
 [1.0 0.0 0.0 ... 1 1 101168.9]
 [0.0 1.0 0.0 ... 1 0 33462.94]]


### Feature Scaling

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train) 
x_test = sc.transform(x_test) 

## PART-2: Building the ANN

### Initialising the ANN

In [8]:
ann = tf.keras.models.Sequential()

2022-06-29 15:43:28.551265: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


### Adding the input layer and the first hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu')) # Rectifier activation function

### Adding the second hidden layer

In [10]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

### Adding the output layer

In [11]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid')) # Binary output(1 or 0) # Sigmoid activation function # for non-binary(0,1,2,3..)---softmax activation function

## PART-3: Training the ANN

### Compiling the ANN

In [12]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])# adam = stochastic gradient decent # binary_crossetropy = for (0/1--output), for multiple categories: categorical_crossetropy = for(0,1,2,3(OneHot Encoded)---output) 

### Training the ANN on the Training set

In [13]:
ann.fit(x_train,y_train, batch_size=32, epochs=100)# epochs means no. of iteratios

Epoch 1/100
250/250 [==============================] - 1s 818us/step - loss: 0.5774 - accuracy: 0.7384
Epoch 2/100
250/250 [==============================] - 0s 803us/step - loss: 0.4670 - accuracy: 0.7975
Epoch 3/100
250/250 [==============================] - 0s 761us/step - loss: 0.4350 - accuracy: 0.8089
Epoch 4/100
250/250 [==============================] - 0s 744us/step - loss: 0.4200 - accuracy: 0.8183
Epoch 5/100
250/250 [==============================] - 0s 736us/step - loss: 0.4063 - accuracy: 0.8274
Epoch 6/100
250/250 [==============================] - 0s 748us/step - loss: 0.3914 - accuracy: 0.8370
Epoch 7/100
250/250 [==============================] - 0s 770us/step - loss: 0.3792 - accuracy: 0.8436
Epoch 8/100
250/250 [==============================] - 0s 805us/step - loss: 0.3704 - accuracy: 0.8481
Epoch 9/100
250/250 [==============================] - 0s 718us/step - loss: 0.3641 - accuracy: 0.8505
Epoch 10/100
250/250 [==============================] - 0s 708us/step - l

250/250 [==============================] - 0s 709us/step - loss: 0.3350 - accuracy: 0.8635
Epoch 80/100
250/250 [==============================] - 0s 696us/step - loss: 0.3345 - accuracy: 0.8637
Epoch 81/100
250/250 [==============================] - 0s 706us/step - loss: 0.3348 - accuracy: 0.8618
Epoch 82/100
250/250 [==============================] - 0s 707us/step - loss: 0.3352 - accuracy: 0.8618
Epoch 83/100
250/250 [==============================] - 0s 708us/step - loss: 0.3346 - accuracy: 0.8627
Epoch 84/100
250/250 [==============================] - 0s 699us/step - loss: 0.3350 - accuracy: 0.8625
Epoch 85/100
250/250 [==============================] - 0s 708us/step - loss: 0.3343 - accuracy: 0.8630
Epoch 86/100
250/250 [==============================] - 0s 712us/step - loss: 0.3347 - accuracy: 0.8615
Epoch 87/100
250/250 [==============================] - 0s 710us/step - loss: 0.3342 - accuracy: 0.8608
Epoch 88/100
250/250 [==============================] - 0s 701us/step - loss:

## PART-4: Making the Predictions and Evaluating the model

### Predicting the results of a single observation

In [14]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))) # Probability 
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5) # 1--exit, 0--stay

1/1 [==============================] - 0s 69ms/step
[[0.01918231]]
1/1 [==============================] - 0s 15ms/step
[[False]]


### Predict the test set results

In [15]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis=1))

63/63 [==============================] - 0s 611us/step
[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [16]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[1528   57]
 [ 208  207]]
0.8675
